#!/usr/bin/env python3
"""Generate the testing dashboard checklist from the canonical Markdown plan."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/FULL_PLAYTHROUGH_TEST_PLAN.md"
OUTPUT = ROOT / "test-dashboard/checklist.json"
SEED = ROOT / "supabase/seed.sql"
ITEM = re.compile(r"^- \[ \] `(?P<id>[A-Z]\d{2})` (?P<body>.*)$")


def plain(value: str) -> str:
    return value.replace("**", "").replace("`", "").strip()


def generate() -> tuple[str, str]:
    source = SOURCE.read_text(encoding="utf-8")
    section = ""
    items: list[dict[str, object]] = []
    section_order: dict[str, int] = {}
    for line in source.splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            section_order.setdefault(section, len(section_order))
            continue
        match = ITEM.match(line)
        if not match:
            continue
        body = match.group("body")
        if " **Pass if:** " in body:
            instruction, expected = body.split(" **Pass if:** ", 1)
        else:
            instruction = body
            expected = "The checkpoint file is created successfully."
        items.append({
            "id": match.group("id"),
            "section": section,
            "sectionOrder": section_order[section],
            "order": len(items),
            "instruction": plain(instruction),
            "expected": plain(expected),
        })
    ids = [item["id"] for item in items]
    if len(items) != 138:
        raise SystemExit(f"Expected 138 checklist items, found {len(items)}")
    if len(ids) != len(set(ids)):
        raise SystemExit("Checklist contains duplicate test IDs")
    payload = {
        "version": hashlib.sha256(source.encode()).hexdigest()[:12],
        "source": "docs/FULL_PLAYTHROUGH_TEST_PLAN.md",
        "count": len(items),
        "items": items,
    }
    encoded = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    sql_rows = []
    for item in items:
        values = [
            payload["version"], item["id"], item["section"],
            item["instruction"], item["expected"], item["order"],
        ]
        rendered = [
            str(value) if isinstance(value, int)
            else "'" + str(value).replace("'", "''") + "'"
            for value in values
        ]
        sql_rows.append("(" + ", ".join(rendered) + ")")
    seed = (
        "-- Generated by scripts/generate_test_dashboard_data.py; do not edit.\n"
        "insert into public.checklist_items "+
        "(checklist_version, test_id, section, instruction, expected, display_order) values\n"
        + ",\n".join(sql_rows)
        + "\non conflict (checklist_version, test_id) do update set "
        "section = excluded.section, instruction = excluded.instruction, "
        "expected = excluded.expected, display_order = excluded.display_order;\n"
    )
    return encoded, seed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered, seed = generate()
    if args.check:
        stale = [
            path.relative_to(ROOT) for path, content in ((OUTPUT, rendered), (SEED, seed))
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("FAIL generated dashboard files are stale: " + ", ".join(map(str, stale)))
            return 1
        print("PASS dashboard checklist and seed: 138 unique tests")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SEED.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    SEED.write_text(seed, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} and {SEED.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
