#!/usr/bin/env python3
"""Generate deterministic postgame Sevii encounter tables for uncovered families."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

from audit_availability import (
    ROOT, evolution_closure, national_targets, parse_ingame_trade_rows,
    parse_scripted_rows, parse_stock_wild_rows, parse_wild_rows, species_to_dex,
)
from m3_evolution_audit import DEFAULT_TABLE, TRANSFORM_METHODS, parse_table

CSV_PATH = ROOT / "data/gen9_reserve.csv"
INC_PATH = ROOT / "data/gen9_reserve_tables.inc"
MAPS = (
    "THREE_ISLAND_BERRY_FOREST",
    "FOUR_ISLAND_ICEFALL_CAVE_1F",
    "SIX_ISLAND_PATTERN_BUSH",
    "FIVE_ISLAND_LOST_CAVE_ROOM1",
    "ONE_ISLAND_KINDLE_ROAD",
    "SIX_ISLAND_RUIN_VALLEY",
    "SEVEN_ISLAND_SEVAULT_CANYON",
    "SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER",
    "FIVE_ISLAND_MEADOW",
    "TWO_ISLAND_CAPE_BRINK",
    "FIVE_ISLAND_MEMORIAL_PILLAR",
    "SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER",
    "SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER",
    "SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER",
    "SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER",
    "SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER",
)
TIMES = ("Morning", "Day", "Evening", "Night")
RATES = (20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1)


def base_rows() -> list[dict[str, str]]:
    return (parse_wild_rows() + parse_stock_wild_rows() + parse_scripted_rows()
            + parse_ingame_trade_rows())


def reserve_seeds() -> list[str]:
    dex_map = species_to_dex()
    targets = national_targets()
    available = evolution_closure({row["species"] for row in base_rows()})
    covered = {dex_map[s] for s in available if s in dex_map}
    missing = targets - covered
    inverse: dict[str, list[str]] = {}
    for species, dex in dex_map.items():
        inverse.setdefault(dex, []).append(species)
    edges = [e for e in parse_table(DEFAULT_TABLE) if e.method not in TRANSFORM_METHODS]
    predecessors: dict[str, set[str]] = {}
    for edge in edges:
        predecessors.setdefault(edge.target, set()).add(edge.source)

    candidates = {dex: min(species, key=lambda s: (s.removeprefix("SPECIES_") != dex.removeprefix("NATIONAL_DEX_"), len(s), s))
                  for dex, species in inverse.items() if dex in missing}
    seeds: set[str] = set()
    while True:
        closure = evolution_closure(available | seeds)
        remaining = {dex for dex in missing if not any(s in closure for s in inverse[dex])}
        if not remaining:
            break
        remaining_species = {candidates[dex] for dex in remaining}
        roots = sorted(s for s in remaining_species
                       if not (predecessors.get(s, set()) & remaining_species))
        if not roots:
            roots = [candidates[min(remaining)]]
        seeds.update(roots)
    return sorted(seeds, key=lambda s: dex_map.get(s, s))


def render(seeds: list[str]) -> tuple[str, str]:
    if len(seeds) > len(MAPS) * len(TIMES) * len(RATES):
        raise RuntimeError("reserve map capacity exceeded")
    rows: list[dict[str, str]] = []
    arrays: list[str] = ["/* Generated by scripts/generate_gen9_reserve.py. */", ""]
    headers = {time: [] for time in TIMES}
    padded = seeds + [seeds[-1]] * (math.ceil(len(seeds) / 12) * 12 - len(seeds))
    for table_index in range(0, len(padded), 12):
        map_index = table_index // (12 * len(TIMES))
        time = TIMES[(table_index // 12) % len(TIMES)]
        map_name = MAPS[map_index]
        mons = padded[table_index:table_index + 12]
        symbol = f"gGen9Reserve{map_index + 1}{time}"
        arrays.append(f"const struct WildPokemon {symbol}Mons[] =")
        arrays.append("{")
        for slot, (species, rate) in enumerate(zip(mons, RATES)):
            level = 50 + min(map_index, 10)
            arrays.append(f"    {{{level}, {level + 3}, {species}}},")
            if table_index + slot < len(seeds):
                rows.append({
                    "species": species, "form": "", "acquisition_method": "wild reserve",
                    "map": map_name, "encounter_type": "land", "badge_requirement": "8 + game clear",
                    "rate": str(rate), "evolution_source": "", "quest": "Gen 9 Sevii Reserve",
                    "notes": f"{time.lower()} deterministic slot {slot + 1}",
                })
        arrays.extend(("};", f"const struct WildPokemonInfo {symbol}Info = {{15, {symbol}Mons}};", ""))
        headers[time].append(
            "    { .mapGroup = MAP_GROUP(%s), .mapNum = MAP_NUM(%s), .landMonsInfo = &%sInfo, "
            ".waterMonsInfo = NULL, .rockSmashMonsInfo = NULL, .fishingMonsInfo = NULL }," %
            (map_name, map_name, symbol)
        )
    for time in TIMES:
        arrays.append(f"#define GEN9_RESERVE_{time.upper()}_HEADERS \\")
        for index, entry in enumerate(headers[time]):
            arrays.append(entry + (" \\" if index + 1 < len(headers[time]) else ""))
        arrays.append("")
    fields = ("species", "form", "acquisition_method", "map", "encounter_type",
              "badge_requirement", "rate", "evolution_source", "quest", "notes")
    from io import StringIO
    output = StringIO()
    writer = csv.DictWriter(output, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue(), "\n".join(arrays) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    seeds = reserve_seeds()
    csv_text, inc_text = render(seeds)
    if args.check:
        ok = CSV_PATH.exists() and INC_PATH.exists() and CSV_PATH.read_text() == csv_text and INC_PATH.read_text() == inc_text
        print(f"Gen 9 reserve: {len(seeds)} family roots; generated files {'current' if ok else 'STALE'}")
        return 0 if ok else 1
    CSV_PATH.write_text(csv_text, encoding="utf-8")
    INC_PATH.write_text(inc_text, encoding="utf-8")
    print(f"Generated {len(seeds)} deterministic reserve encounters across {math.ceil(len(seeds) / 48)} maps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
