#!/usr/bin/env python3
"""Generate deterministic regional migration pools for the M7 DexNav selector."""
from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / ".upstream/cfru/include/generated/m7_habitat_groups.h"
CONTRACT = ROOT / "data/habitat_migration_groups.csv"
RANGES = ((1, 151), (152, 251), (252, 386), (387, 493), (494, 649),
          (650, 721), (722, 809), (810, 905), (906, 1025))


def pools():
    pokedex = (ROOT / ".upstream/cfru/include/constants/pokedex.h").read_text(encoding="utf-8")
    values = {name: int(value) for name, value in re.findall(
        r"^#define\s+(NATIONAL_DEX_[A-Z0-9_]+)\s+(\d+)", pokedex, re.M)}
    mapping = re.findall(
        r"\[(SPECIES_[A-Z0-9_]+)\s*-\s*1\]\s*=\s*(NATIONAL_DEX_[A-Z0-9_]+)",
        (ROOT / ".upstream/dpe/src/Species_To_Pokdex_Table.c").read_text(encoding="utf-8"))
    base = {}
    for species, national in mapping:
        if species.removeprefix("SPECIES_") == national.removeprefix("NATIONAL_DEX_"):
            base[values[national]] = species
    for species, national in mapping:
        base.setdefault(values[national], species)
    base[550] = "SPECIES_BASCULIN_RED"
    base[774] = "SPECIES_MINIOR_RED"
    base[892] = "SPECIES_URSHIFU_SINGLE"
    legendary = {row["species"] for row in csv.DictReader(
        (ROOT / "data/legendary_encounters.csv").open(encoding="utf-8"))}
    result = []
    for start, end in RANGES:
        # Sixteen evenly distributed representatives keep the inserted table
        # compact while making every generation visible across different maps.
        candidates = [base[number] for number in range(start, end + 1)
                      if base[number] not in legendary]
        nums = [(len(candidates) - 1) * i // 15 for i in range(16)]
        result.append([candidates[index] for index in nums])
    return result


def render(groups):
    lines = ["/* Generated by scripts/generate_m7_habitat.py. Do not edit. */",
             "#ifndef GUARD_GENERATED_M7_HABITAT_GROUPS_H",
             "#define GUARD_GENERATED_M7_HABITAT_GROUPS_H", ""]
    for i, group in enumerate(groups, 1):
        lines.append(f"static const u16 sM7MigrationGroup{i}[] = {{{', '.join(group)}}};")
    lines.extend(["", "static const u16 *const sM7MigrationGroups[] = {"])
    lines.extend(f"    sM7MigrationGroup{i}," for i in range(1, 10))
    lines.extend(["};", "#define M7_MIGRATION_GROUP_SIZE 16", "#define M7_MIGRATION_GROUP_COUNT 9", "#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(pools())
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if old != content:
        if args.check:
            print("STALE .upstream/cfru/include/generated/m7_habitat_groups.h")
            return 1
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(content, encoding="utf-8")
        print(f"Wrote {OUT.relative_to(ROOT)}")
    rows = list(csv.DictReader(CONTRACT.open(encoding="utf-8")))
    for row in rows:
        row["implementation_status"] = "IMPLEMENTED_UNVERIFIED"
    expected = "generation,region,group,implementation_status\n" + "".join(
        f'{row["generation"]},{row["region"]},{row["group"]},{row["implementation_status"]}\n' for row in rows)
    if CONTRACT.read_text(encoding="utf-8") != expected:
        if args.check:
            print("STALE data/habitat_migration_groups.csv")
            return 1
        CONTRACT.write_text(expected, encoding="utf-8")
        print("Wrote data/habitat_migration_groups.csv")
    print("M7 migration pools: 9 groups x 16 generated species")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
